### PR TITLE
Pilgrim, an 8-bit inspired theme 👾

### PR DESCRIPTION
**Pull request by gnclmorais**
#### Pilgrim

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders a compiled CSS file?

8-bit inspired, developed with the inspiration and help of NES.css in a few elements.
[image](https://codepen.io/gnclmorais/full/KKVLBaP)

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hey @gnclmorais - this is so fun! I especially love the speech bubbles around the featured styles!

Here's the deploy preview: https://deploy-preview-26--moderncss-styles.netlify.app/styles/pilgrim/

I know the rainbow hover on links is important to the theme, but I'd ask for a few small tweaks on it to make it more inclusive to our visitors who may have motion sensitivities or vision deficiencies:
- slow down the transition, and possibly stop after 2-3 iterations (the TL;DR of motion guidelines related to blinking/flashing is not more than 3 "blinks" per second and that the animation stops within 5 seconds)
- select a "rainbow" that meets 3:1 contrast for each color over white or black (3:1 is acceptable since you are using a larger and bold font)
- include this animation in the rule that will remove it for the `prefers-reduced-motion` media query

Thanks for participating, I'm excited to get this added!

**Comment by 5t3ph** [comment]
@gnclmorais Good work on the improvements! I played with it a bit in Inspector to make sure the contrast was ok both over white and black (considering your nav links) and I have a slight adjustment for your gradient:

```
linear-gradient(    90deg,    #ff2400,    #a17607,    #11ac2b,    #11a4ac,    #4F77E6,     #dd00f3  )
```

I also reduced the values to make it a bit less of a "flashing" effect from the color changes.

Since the animation spans 5s, please drop the `2` from `animation: rainbow 5s linear` so that it only runs 1x.

Then I think it will be good to get added!

**Comment by gnclmorais** [comment]
Good shoutout, the link animation only runs now once and it has less colours, like you suggested. 🙂  It’s a shame the animation can’t be more vibrant and “electric” (like 8-bit games!) but I understand why. Thanks for the suggestions!

**Comment by 5t3ph** [comment]
Awesome, approved!

**Comment by gnclmorais** [comment]
Success! 🏆

**Comment by 5t3ph** [comment]
Hey @gnclmorais if you haven't already, I'd like to invite you to subscribe to updates to keep informed of new features: https://stylestage.dev/subscribe/

**Pull request merged**
