### PR TITLE
Yellowed

### PR DESCRIPTION
**Pull request by SowmyaSeshadri**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @SowmyaSeshadri  - first off, I love this! A couple small things to fix up:

The contrast needs updatd for the `.skip-link`:
image

A visible `:focus` style needs to be added for all of the "button" styled links.

Not required but an option - you may want to update your link `:hover` styles that trigger motion to also include `:focus-within`.

Here there is a dueling issue where I would propose not allowing the navigation to overlap the main content area:
image

There is an overflow issue on in-between breakpoints as well, and I'm unable to even scroll to view the cut-off content (affects more than just the `blockquote` shown here):
image

Let me know when you've made these adjustments and I'll redeploy the preview! https://deploy-preview-77--moderncss-styles.netlify.app/styles/yellowed/

**Comment by SowmyaSeshadri** [comment]
@5t3ph Thanks for the quick review! I shall update these and let you know!

**Comment by SowmyaSeshadri** [comment]
Hi, @5t3ph I've updated the below items - 
1. Fixed the 'Skip to main content' contrast issue
2. Added a visible style for all button styled links.
3. Fixed the overlap issue.
4. Fixed the blockquote width.

Can you please redeploy?

**Review by 5t3ph — APPROVED** [review]
@SowmyaSeshadri fantastic work with the updates, publishing now!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Pull request merged**
