### PR TITLE
Hackytoberfest

### PR DESCRIPTION
**Pull request by JordanaHarrison**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @JordanaHarrison - a few things to adjust according to the preview: https://deploy-preview-68--moderncss-styles.netlify.app/styles/hackytoberfest/

Please troubleshoot what may be happening here:
image

And, the contrast fails on hover of the "buttons":
image

Please resolve the overlap once the user scrolls to the bottom:
image

The `.skip-link` also lost it's color:
image

The "button" background vs. it's surrounding should meet at least 3:1 contrast as well:
image

Let me know when these things are resolved and I will redeploy the preview, thanks!

**Comment by JordanaHarrison** [comment]
Hi @5t3ph, I made the required changes to the stylesheet that is linked in pull request, can you redeploy?

**Review by 5t3ph — APPROVED** [review]
@JordanaHarrison thanks for working on those updates, ready to publish! 

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Comment by JordanaHarrison** [comment]
Thanks! I actually learned a few new tricks from doing this. It was fun!

**Pull request merged**
