### PR TITLE
Add My Stylesheet

### PR DESCRIPTION
**Pull request by dominicduffin1**

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hey, I like where this is going! Here is the preview link: https://deploy-preview-3--moderncss-styles.netlify.app/styles/purplify-and-pastel/

I'm looking at it in Chrome and a few things to fix:
- It would be best if the .profile background doesn't block the rest of the page - as in, we should be able to click things behind it.
- Also for the profile there is an issue of the Twitter button overlapping the Twitter title
- There is something on small viewports that is preventing a full responsive resize.
- the `.skip-link` style was missed (first item on the page)

**Comment by 5t3ph** [comment]
^ let me know when you think you've resolved those things and updated your stylesheet, and I'll re-deploy the preview

**Comment by dominicduffin1** [comment]
I think all the issues are now fixed, and I've added a couple of responsiveness improvements in addition to fixing the bug. Let me know if there's anything else to fix.

I notice you've added a 'Support Style Stage' banner at the bottom - if you could point me to an updated HTML I could add some rules to incorporate that into my style.

**Comment by 5t3ph** [comment]
@dominicduffin1 Much improved! One final suggestion would be to add a media query to reduce the padding for paragraphs on mobile to perhaps 1rem instead of 5rem - the content is quite narrow:

screenshot with padding styles highlighted

**Comment by dominicduffin1** [comment]
@5t3ph Will do!

**Comment by 5t3ph** [comment]
@dominicduffin1 oh i forgot to mention that hte sponsor area isn't available for restyle - it will inherit font which is fine but otherwise should remain untouched.

**Comment by dominicduffin1** [comment]
@5t3ph I've updated it!

**Comment by dominicduffin1** [comment]
> @dominicduffin1 oh i forgot to mention that hte sponsor area isn't available for restyle - it will inherit font which is fine but otherwise should remain untouched.

Ah ok - that's fine :)

**Comment by 5t3ph** [comment]
@dominicduffin1 perfect! I'll resolve the merge conflict and get it published to the preview link 🙌

**Pull request merged**
