### PR TITLE
Neon Beetles

### PR DESCRIPTION
**Pull request by barbaraaliverti**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

Hope I'm still in time for Hacktoberfest! I'm a beginner but I learned a lot from this project and had a great time :)

Thanks!

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @barbaraaliverti - Great job! I need to still check contrast but on mobile there is overlap from the floating navigation background not being tall enough, and due to the inserted sponsor footer at the bottom: 
EB00547A-A7BD-4F71-8399-D7DE7F518A25

**Comment by barbaraaliverti** [comment]
Hi, @5t3ph! Thank you for your review. I just made a few changes to the stylesheet to fix these layout problems and I updated my file (same link). Please let me know if this works or if I better open a new pull request. Thanks :)

**Comment by 5t3ph** [comment]
@barbaraaliverti - a few contrast and other accessibility things to resolve:

The `.skip-link` needs to be made visible at least on `:focus` - check out the original styles if you're not sure how to do that!

The links need to meet 4.5:1 contrast with your background color, and also either keep their original underline add some other effect to help them stand out as links:
image

These also need to have the gradient darkened so that the text meets 4.5:1 contrast across the whole gradient:
image

Same with your button styles (or for either of these you can use dark text instead of darkening the gradient):
image

And same with the `:hover` state on these card links:
image

These links are stacking on each other:
image

There is still overlap of the sponsor footer - just doing a quick experiment it seems like you may resolve it with adding `padding-bottom: 3rem` to your styles for `body`:
image

Finally, can you verify for me that you either created the beetle illustrations or that they are licensed for free use, or you purchased them to use? Thanks!

I'm glad you learned some new things, and I look forward to the fixes so we can get it added!

**Comment by barbaraaliverti** [comment]
Hi, @5t3ph! Thanks for taking the time to review my work.

I just updated my stylesheet with all the points you made and a few more corrections that didn't occur to me before.

I changed this blue shade to correct the contrast and added a dashed underline to all links:

image

Also fixed all the contrast problems that you mentioned and the stacking buttons in the footer. 

image

image

image

image


As for the beetle illustrations, they are licensed for free use - I made the backgrounds on [Canva.com](canva.com) using free images. As Canva states in their terms of use, [all their free media can be used for free for commercial and noncommercial use](https://about.canva.com/license-agreements/free-media/).

Thanks again :+1:

**Comment by 5t3ph** [comment]
@barbaraaliverti great work on the updates, this is suuuuper close!

What I'm showing in this screenshot is that the profile info is covering up the `.skip-link`:
image

And it looks like (and I just learned this!) there is an additional property you can use to fix the overlap of your underline style, `text-underline-position: under;` - here's what it currently looks like _without_ that property for me in Chrome:
image

Finally, looking at this on Chrome on iPhone for some reason the background image is really blown up and blurry (it doesn't do this when shrining the viewport on desktop) - I wonder if removing `background-size: auto` would resolve it? It's very strange, I'm not sure what else is causing it.

I'll look out for your updates so we can merge it in time for hacktoberfest!

**Comment by barbaraaliverti** [comment]
Ok, I think I finally understood what the `.skip-link` button is supposed to do! :laughing:  It's working properly and it's visible on `:focus` now.

image

I also added `text-underline-position: under` to my links and it does look better! And I didn't know the layout could look so different on different browsers (I'm using Firefox), the colors look a bit too strong on Chrome :laughing: It's good to know that I should always test my stylesheets on different browsers.

Finally, I changed the `background-size` to `cover`, hope this fixes the background problem.

Thanks, @5t3ph!

**Review by 5t3ph — APPROVED** [review]
@barbaraaliverti fantastic, publishing now!

You should consider participating in the giveaway which ends tonight: https://dev.to/5t3ph/a-giveaway-to-celebrate-50-stylestage-dev-stylesheets-4220

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Pull request merged**
