### PR TITLE
tour-in-rio

### PR DESCRIPTION
**Pull request by Maujor**
### New Stylesheet Submission:

- [] Have you followed the guidelines in our Contributing document?
- [] Have you checked to ensure there aren't other files using the same name as yours?
- [] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [] Do your styles pass proper contrast for accessibility?
- [] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [] Did you style the `.skip-link`?
- [] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by Maujor** [comment]
May I know what is wrong with my submission?

**Comment by 5t3ph** [comment]
@Maujor I appreciate the creativity with this one!

Unfortunately, the image in this section is so detailed it makes the text hard to read. Perhaps you can add some top padding to include the image within so that it's not directly behind the text?
image

Additionally, these buttons have too low of contrast. With that text size and the bold it will need to be over 3 at the least:
image

Finally, there are some content overlap issues for small (mobile) viewports:
image

**Comment by Maujor** [comment]
@5t3ph Thanks for advices!
I fixed the issues, Please have a look.
Merry Christmas.

**Comment by 5t3ph** [comment]
@Maujor I see the update to the background image, but the mobile styles still have some trouble spots. Please check the site down to at least 375px wide and resolve any issues you see with overlapping content or content breaking out of the designs (like the cloud images).

The contrast on the "buttons" has also gotten a bit worse as well. If you change your opacity from `0.6` to `0.65` it will pass contrast!

**Comment by 5t3ph** [comment]
@Maujor closing for now but if you find time to address my previous comment, please re-submit, thanks!

**Pull request closed without merging**
