### PR TITLE
Calm

### PR DESCRIPTION
**Pull request by trip19**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
@trip19 - thanks for contributing! There are a few things to fix up to meet the guidelines before we can add this to the gallery.

- Resolve the color contrast of the text - [here's a link to learn more about that and to test your colors](https://webaim.org/resources/contrastchecker/)
- Turn off the animation for users who prefer reduced motion - [here's an example from the original stylesheet](https://github.com/5t3ph/stylestage/blob/main/src/styles/css/main-stage.css#L84,L91)
- The `.skip-link` needs to be made visible at least on focus - [here's how it's done in the original](https://github.com/5t3ph/stylestage/blob/main/src/styles/css/main-stage.css#L632,L650)

And there's a few parts that break on resize of the browser:
image
image
image

Let me know in a new comment when you've updated your stylesheet, and I'll rebuild the preview and take another look!

**Comment by trip19** [comment]
hey ,I don't understand how to fix the color contrast .I looked at the link provided but i don't know what to do. Do ii need to change the text color?

**Comment by trip19** [comment]
Hey , I've changed the stylesheet. Please check

**Comment by 5t3ph** [comment]
@trip19 great job resolving the issues! The very last thing is choosing a dark color for the `.skip-link` when it shows up:
image

**Comment by trip19** [comment]
i made the required changes. Please check.

**Comment by 5t3ph** [comment]
Hi @trip19 - you'll want to change your remote version like you did with the first round of changes. That's because the site "scrapes" from your URL, so if you change it in the repo it will get overwritten when it scrapes again (which is a nightly process on the live site). So make the change in `trip19/stylestage/main/src/styles/css/calm.css` and remove the change to the CSS here and then I can check again!

**Comment by trip19** [comment]
Hey, I did the changes. Please check

**Review by 5t3ph — APPROVED** [review]
@trip19 ok, ready to publish! Thanks for sticking with it to work through the feedback!

**Pull request merged**
