### PR TITLE
Vibrant

### PR DESCRIPTION
**Pull request by Lakshmikant-2001**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hey @Lakshmikant-2001 - nice, really close to ready!

Can you apply the same `:focus` style to your glowing buttons as is on the other ones with the solid border? The current style isn't quite strong enough to allow someone relying on visual focus styles to follow that these buttons have the focus:
image

**Comment by Lakshmikant-2001** [comment]
@

> Hey @Lakshmikant-2001 - nice, really close to ready!
> 
> Can you apply the same `:focus` style to your glowing buttons as is on the other ones with the solid border? The current style isn't quite strong enough to allow someone relying on visual focus styles to follow that these buttons have the focus: image

@5t3ph Check it now, ma'am!
ss-focus-fix

**Comment by 5t3ph** [comment]
@Lakshmikant-2001 hey, sorry, i wasn't complete enough in my feedback - if you could apply the same update to this other one it'll be ready!
image

**Comment by Lakshmikant-2001** [comment]
> @Lakshmikant-2001 hey, sorry, i wasn't complete enough in my feedback - if you could apply the same update to this other one it'll be ready! image

@5t3ph fixed it ma'am!

**Comment by Lakshmikant-2001** [comment]
@5t3ph any updates ma'am?

**Review by 5t3ph — APPROVED** [review]
@Lakshmikant-2001 thanks for sticking with it, publishing now!

**Comment by Lakshmikant-2001** [comment]
> @Lakshmikant-2001 thanks for sticking with it, publishing now!

@5t3ph Thanks for the opportunity ma'am!

**Comment by Lakshmikant-2001** [comment]
> @Lakshmikant-2001 thanks for sticking with it, publishing now!

@5t3ph PR not merged yet ma'am!

**Comment by Lakshmikant-2001** [comment]
@5t3ph Thanks for the opportunity mam!

**Pull request merged**
