### PR TITLE
Neomorphism-Design

### PR DESCRIPTION
**Pull request by Manoranjan-D**
### New Stylesheet Submission:

Neomorphism-Design

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
@Manoranjan-D good start! There are a couple things to update to meet the guidelines. Once you update these, let me know and I'll rebuild the preview to review!

- the `.skip-link` needs to become visible at least on `:focus`
- the contrast currently doesn't pass for the links with your `primary` color, it needs to be dark enough to pass with at least 4.5:1 ratio
- once the purple is darkened, it probably will make the links blend into the paragraph text, so it would be a good idea to let those links be underlined to help them stand out

**Comment by Manoranjan-D** [comment]
Hi,
I have done necessary change to the file, kindly review and let me know if any other changes have to be  done from my end 
Thank you

**Comment by Manoranjan-D** [comment]
Hi,
I have done necessary change to the file, kindly review and let me know if any other changes have to be done from my end
Thank you

**Review by 5t3ph — APPROVED** [review]
@Manoranjan-D looks good, adding now! Thanks for participating!

**Pull request merged**
