### PR TITLE
Jet Set

### PR DESCRIPTION
**Pull request by cbirdsong**
### New Stylesheet Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders a compiled CSS file?

The tricks I've used for adding text stroke and/or wrapper shapes on basically every link generate false positives for contrast issues. I think the only real edge case is the text in the header - let me know if you think I need to change it.

### CODE REVIEW

**Comment by cbirdsong** [comment]
Hmm, something appears to have gone wrong? The [stylesheet link](https://cbirdsong.github.io/stylestage-jet-set/style.css) works for me?

**Comment by 5t3ph** [comment]
@cbirdsong it worked! https://deploy-preview-44--moderncss-styles.netlify.app/styles/jet-set/

Lots of creative things happening! I do have an issue in Chrome when I test `prefers-reduced-motion` where the headline title and effect is thrown out of alignment (or maybe that's intentional!)

You may want to create one more template area to accommodate the `#sponsor-footer` - it's typically not available to style but in this case it just needs to be assigned an area 👍

Please also make sure the `.skip-link` is visible at least on focus.

Let me know when those updates are made and I'll redepoy the preview!

**Comment by cbirdsong** [comment]
@5t3ph Should be all fixed up, along with some horizontal overflow issues. I also had a typo in my reset `@import`, which made a bunch of things act a bit squirrelly.

**Comment by cbirdsong** [comment]
@5t3ph can you pull it again? I adjusted the breakpoint for when the header rearranges itself.

**Comment by 5t3ph** [comment]
@cbirdsong no problem, updated!

**Comment by cbirdsong** [comment]
@5t3ph One more time? (Should I just submit a new PR for this?)

**Comment by 5t3ph** [comment]
@cbirdsong updated on the live site!

No need for new PR - since it scrapes your link there wouldn't be any actual changes to place in a PR. This works fine since it at least keeps the conversation in context, thanks for checking!

**Pull request merged**
