### PR TITLE
Create eighties-synthwave.json

### PR DESCRIPTION
**Pull request by kevin-powell**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

Sorry it took so long to get the request in from when I finished working on it! 😅

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hey @kevin-powell - psyched to see this in the queue!

Are the fonts you chose available to @import into your stylesheet from Google fonts? Or can you update to absolute URLs w/o a CORS issue? Here's your deploy preview:
https://deploy-preview-89--moderncss-styles.netlify.app/styles/eighties-synthwave/

For the gradient text - I just learned this - instead of setting the `color` to transparent (breaking accessibility for browsers where it's not supported) keep `color` as a fallback color and use `-webkit-text-fill-color: transparent;` 👍 

Minor contrast issues:

Hover color of links over white:
image

The `:focus` state should maintain 3:1 contrast with the surface behind it, so maybe include a 2px black border to resolve? (Latest WCAG draft is recommending 2px border when the contrast doesn't suffice)
image

At this font-size, this contrast should meet 4.5:1 (if you darken the magenta for the first issue first, then re-check here as this will change again):
image

And if you use Inspector on the deploy preview link to find the `sponsor-footer` in the DOM - could you work out how to allow it to sit in your grid? No other styling is permitted but it does need to be visible! (Congrats on the first design which has accidentally hidden it haha - except mobile ;) )

After you've made the updates, comment back and I'll redeploy the preview!

**Comment by kevin-powell** [comment]
I think I got them all. Was a bit confused with the contrast issues on white, till I remembered I created a light mode in a media query on one of the live streams, and I didn't spend much time on it. Everything should look better, and I think I got all the contrast issues. I also believe this fixes the problem with the outline everywhere, but I can add the border if needed.

I think the sponsor footer was filling into one of my unnamed grid areas, so I created one for it :). Guess I should be proud that I'm the first one to break it, lol.

**Comment by kevin-powell** [comment]
I *think* everything is good now. 
As a heads up, the reason I broke the sponsor thing was I used `aside:last-of-type` to select one of them. So that placed it on the grid in the wrong place, and mucked up the placement of one of the asides at the same time. I don't even know why I did it that way to be honest, lol. But it's been fixed :D.

**Review by 5t3ph — APPROVED** [review]
@kevin-powell whoohoo, good to go!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Pull request merged**
