### PR TITLE
Create Vice-City-Vaporwave.json

### PR DESCRIPTION
**Pull request by builtbybea**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @builtbybea - thanks for your contribution! I love the background gradient and texture and idea for this theme!

To be accepted, please refine your typography so that it's a bit more legible to meet our accessibility requirement. Relying on text stroke will not be cross-browser compatible, leaving out some users from reading the content :) It also to my eyes is fairly hard to read. It's particularly hard to read over the header graphic for the h1 and links.

You may try text-shadow, or pick a more bold font so that it doesn't cut into the letters as much?

Also instead of shrinking the font-size for smaller viewports, perhaps allow the grid columns to stack sooner - the font-size get's quite small to read!

Lastly, please allow the `.skip-link` to be visible at least on `:focus` - review the Main Stage original stylesheet for how to do this if you're not sure! A tip on that is when you tab into the page, it should be the first link that receives focus.

Let me know when your edits are made, and I will rebuild the preview for us to review again:
https://deploy-preview-86--moderncss-styles.netlify.app/styles/vice-city-vaporwave/

Thanks, looking forward to the updates! 🌴

**Comment by builtbybea** [comment]
Hi @5t3ph the current font displayed on deployed is different from my original font 
Screenshot 2020-12-13 at 10 06 19
Screenshot 2020-12-13 at 10 09 27

Will this change once staged?

I'll try the text-shadow, because I really want that font family 😣
I'm a bit confused, what would do mean allow the grid columns to stack sooner?

**Comment by 5t3ph** [comment]
Hi @builtbybea - sorry for the delay! The build process copies your stylesheet to the website so the links to your fonts are broken. You will need to choose web fonts that are available on something like Google Fonts and then use the @import method so that it is included directly in your stylesheet. Sorry for missing that before, that makes sense why the fonts were tricky 👍 

However - the comment re: not relying on text strokes is still important to keep in mind in terms of the best support of legibility for the most users, particularly for the white text on a white background.

As for the "stacking" comment - it looked like you were dropping the font size quite a bit for smaller viewports and I was intending to suggest you let the columns stack on top of each other at a larger viewport size instead of shrinking the text so much for the sake of keeping the columns.

And don't forget the `.skip-link` as noted before, too!

Looking forward to the updates! Comment when they are complete and I will trigger a rebuild of the preview to review again.

**Comment by 5t3ph** [comment]
Hi @builtbybea - I'm following up on if you plan to resolve the issues.

I hope you were enjoying some time off though first, haha! Let me know if my comments make sense!

**Comment by builtbybea** [comment]
Hi Steph,
Sorry for the delay! Yep, I'll get to making edits and changes. Just busy studying and trying to relax over the holiday

The only thing I'm upset about is having to potentially change my fonts, they are working fine when I've deployed them to Netlify. Is there a way that I can use custom fonts - I think it's been used in other style stage stylesheets?

**Comment by 5t3ph** [comment]
@builtbybea yup, other folx have either done an @import from google fonts, or if they are self-hosting the font, then you can do it from your own domain _if_ it's not blocked by CORS. Another person tried to link to fonts hosted on Netlify and hit a CORS issue and they were able to switch to pointing to the fonts as hosted on the Github pages version so that may be something to try if they are not available on google fonts?

**Comment by 5t3ph** [comment]
Hi @builtbybea - let me know if you plan to update this! Or if you maybe did and we just need to rebuild the preview to take a look. Hope to hear from you, thanks!

**Comment by 5t3ph** [comment]
@builtbybea - Hi! Going to close this for now, but if you are able to update in the future to resolve the fonts, definitely would love to see this in the gallery! See my previous comments for a couple ideas about the fonts issue.

**Pull request closed without merging**
