### PR TITLE
Animado

### PR DESCRIPTION
**Pull request by Elisangelamsilva**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @Elisangelamsilva - you may still be working on this, but the color contrast issues will need to be resolved before this is accepted. If you need help on how to check that, let me know! There are browser tools and online tools available.

Here is your preview so far: https://deploy-preview-75--moderncss-styles.netlify.app/styles/animado/

**Comment by Elisangelamsilva** [comment]
Hi @5t3ph, thanks for the tips. 
I updated the styles with the fix of the contrast.

**Comment by 5t3ph** [comment]
@Elisangelamsilva good job on the contrast! A few more items I noticed:

Missing bringing the `.skip-link` into view - it needs to at least become visible on `:focus`

A few links need to have an underline or other style added to ensure they are visually noticeable as a link, including the following:
image
image
image

These elements could use a bit of space between them:
image

This text that is shrinking will need to not go below 18.5px to meet contrast:
image

**Comment by Elisangelamsilva** [comment]
Hi @5t3ph, I finished the fixes.

**Review by 5t3ph — APPROVED** [review]
@Elisangelamsilva nice work, publishing now!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Pull request merged**
