### PR TITLE
Emphasis

### PR DESCRIPTION
**Pull request by d-cs**
### New Stylesheet Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders a compiled CSS file?

### CODE REVIEW

**Comment by d-cs** [comment]
This is more of a jokey style, uses Sans Forgetica to attempt to get the reader to remember a key paragraph. Colours selected to improve readability 😅

**Comment by 5t3ph** [comment]
@d-cs haha, nicely done! double check that you're happy with it: https://deploy-preview-21--moderncss-styles.netlify.app/styles/emphasis/

note the sponsor area is not available to style directly

**Comment by d-cs** [comment]
@5t3ph I had a look, Netlify's workflow is fantastic! I'm happy if you are 😄

**Comment by 5t3ph** [comment]
@d-cs great, I'll get it merged!

here's a link to subscribe for future updates like added styles or new features: https://stylestage.dev/subscribe/

**Pull request merged**
