### PR TITLE
Drafter

### PR DESCRIPTION
**Pull request by pinkishpanda**
### New Stylesheet Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders a compiled CSS file?

### CODE REVIEW

**Comment by 5t3ph** [comment]
@pinkishpanda this is very cool!

A couple small things:
- the focus state in the header and in the footer isn't switching the text color right now so it seems to disappear on buttons, and for the text links it looses contrast by keeping it white
- for the orange buttons to pass contrast, can you try changing the border color to something like `#AD6646`? The button background should have at least 3:1 contrast with the surface it's on and changing the border color to fix that counts (tested in inspector I think it still keeps the integrity of your design, i hope you feel the same!) you can pick another color as long as it is at least 3:1 over both your lighter tan and darker tan (no border is needed on the buttons in the header and footer)

Thanks for participating! Let me know when those things are updated and I'll redeploy the preview: https://deploy-preview-39--moderncss-styles.netlify.app/styles/drafter/

**Comment by pinkishpanda** [comment]
Hi @5t3ph thanks for spotting those! I've made adjustments to address the issues. Appreciate it if you could redeploy the preview. Thanks for reviewing! :)

**Comment by 5t3ph** [comment]
@pinkishpanda Great job on those updates! I also realized the main nav is covering the `.skip-link` - if you could allow that to be visible above the nav at least when it receives focus we can get this published. Thanks!

**Comment by pinkishpanda** [comment]
@5t3ph Ah okay! Thanks for picking that up. The `.skip-link` should now be visible when it receives focus 😄

**Pull request merged**
