### PR TITLE
Add Comic theme

### PR DESCRIPTION
**Pull request by kathykato**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

The header `h1` text may generate a false positive for contrast issues. Please let me know if I would need to fix something.

### CODE REVIEW

**Review by 5t3ph — APPROVED** [review]
@kathykato this is soooo cool! Publishing now!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Comment by kathykato** [comment]
@5t3ph Awesome! Thank you so much!

I noticed in the preview that the fonts are not loading. I updated the stylesheet link through CodePen. I think the fonts should be displaying properly now?

**Comment by 5t3ph** [comment]
@kathykato I triggered a rebuild and I believe they are loading now, sorry I missed that! https://stylestage.dev/styles/comic/

**Comment by kathykato** [comment]
No worries! Thanks again! 😀

**Pull request merged**
