### PR TITLE
CSS CLI

### PR DESCRIPTION
**Pull request by hexagoncircle**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hey @hexagoncircle - this is awesome!

Have a look and see if you want to try to add padding or something around the sponsor footer (it is not directly styleable) and I can redeploy the preview after you make changes. If you're ok with it, we can publish as is!

https://deploy-preview-52--moderncss-styles.netlify.app/styles/css-cli/

**Comment by hexagoncircle** [comment]
Thanks, @5t3ph!

I've added a bottom margin to the sponsor block [in my CSS](https://codepen.io/hexagoncircle/pen/rNewaGg). Firefox seems to lose the bottom padding that was originally applied on all sides of the body (on CSS [line 61](https://codepen.io/hexagoncircle/pen/rNewaGg)) so I had to instead apply it to the `page-footer` and now the `sponsor-footer`. If you'd rather that the `sponsor-footer` had no styling directly applied to it, I can try to figure out another way to handle it.

**Comment by 5t3ph** [comment]
Good news - it worked: https://stylestage.dev/styles/css-cli/

**Comment by hexagoncircle** [comment]
Awesome! I've subscribed for updates as well. Thanks for letting me participate. I'm loving this throwback to CSS zen garden! 😄

**Pull request merged**
