### PR TITLE
Blue-Beast

### PR DESCRIPTION
**Pull request by KiranShrinivaas8367**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by poloband** [comment]
GitHub is the shit to me as well.

**Comment by 5t3ph** [comment]
@KiranShrinivaas8367 - sorry for the delay!

There is one color contrast issue which is the grey used for your links - it needs to meet at least 4.5:1 contrast and is currently ~4.11:1, let me know if you need help figuring that out. There are many tools out there to help evaluate!

image

Let me know once you update your styles and I'll rebuild the preview to check.

**Comment by KiranShrinivaas8367** [comment]
@5t3ph I have updated the contrast ratio issue mentioned above.

**Review by 5t3ph — APPROVED** [review]
@KiranShrinivaas8367 update passes, publishing now! Thanks for participating :)

**Pull request merged**
