### PR TITLE
Purpleland

### PR DESCRIPTION
**Pull request by Dawntraoz**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

Hi :) I read the whole guidelines, I took care and check everything with WAVE extension and my mobile also!
If anything else is needed, I'm here to fix it 🎉

Thanks in advance for this awesome project 💜

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @Dawntraoz - a few things to adjust from reviewing your preview: https://deploy-preview-69--moderncss-styles.netlify.app/styles/purpleland/

I appreciate the creativeness of placing the "current staged" banner at the top, but unfortunately, I think in this case it's too far removed from the DOM order for keyboard users who would be jumped way back up quite jarringly - can you come up with either a floating solution or allow it to sit in it's original place with otherwise the same styling?

Next, I think adding some `padding-bottom` on `body` would resolve this overlap scenario on the sponsor footer (you cannot directly style the sponsor footer): 
image

While it's totally fine to add icons, I think the reduction to just icons on smaller viewports in the nav makes the link purpose not recognizable enough so I would encourage you to find an alternative way to reduce the nav while still keeping visible labels.

I see you have imported the Google fonts but it looks like they are not quite being applied so that may need troubleshooting as well.

Finally, please expand your `prefers-reduced-motion` rule to include at least `:before` so that it removes the visible animation from the link "buttons" on hover.

**Comment by Dawntraoz** [comment]
Hi @5t3ph I've just update the repository with the changes you mentioned! The fonts were just a typo when adding weights u.U hahahaha But now it's working!!

Let me know if everything is okey now :) Thanks for your quick feedback!!

**Comment by 5t3ph** [comment]
@Dawntraoz almost there :) The floating `.profile` overlaps the main text now so perhaps narrow the `.container` `max-width` to prevent clashing, and end the float behavior sooner (wider breakpoint)? Or revert to the banner style and let it stay in the original DOM position?

image

**Comment by Dawntraoz** [comment]
You're right, I add it only in more than 1600px now 💜

**Review by 5t3ph — APPROVED** [review]
@Dawntraoz great, thanks for updating it!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Pull request merged**
