### PR TITLE
trafalgar.json

### PR DESCRIPTION
**Pull request by mandrew**
Create trafalgar.json and added style json file content

### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
@mandrew this is super fun! The only minor thing is to assign the sponsor panel to be able to stretch the full grid width (no extra styling other than what's needed to do that) - here's the preview so you can see that issue: https://deploy-preview-114--moderncss-styles.netlify.app/styles/trafalgar/

Let me know when you've made the change in your stylesheet and I'll rebuild the preview!

**Comment by mandrew** [comment]
@5t3ph try now? 

Thanks! The template is a salute to how I learned CSS back when I first started working. My boss told me to create the base layout as a Mondrian painting, just so I could visualise how everything worked :)

**Review by 5t3ph — APPROVED** [review]
@mandrew great! Publishing now 🚀

**Comment by mandrew** [comment]
Thanks! @5t3ph 🎉

**Pull request merged**
