### PR TITLE
Add Blueprint.css

### PR DESCRIPTION
**Pull request by colabottles**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
hey @colabottles - I was baffled why this wasn't included in the deploy, then realized you created your file as `.css` instead of `.json` 😊 If you could resolve that, then we can see a deploy preview, thanks!

**Comment by 5t3ph** [comment]
@colabottles please see previous comment, but I reviewed on the CodePen as well and the "TL;DR" is getting cut off on the left side on wider screens, and the red isn't quite meeting contrast requirements. I also wasn't sure if you wanted to keep the "Ooh scale" `blockquote::after`.

After you resolve those and the file time committed here, we'll take another look and get it published ✨

**Comment by colabottles** [comment]
> @colabottles please see previous comment, but I reviewed on the CodePen as well and the "TL;DR" is getting cut off on the left side on wider screens, and the red isn't quite meeting contrast requirements. I also wasn't sure if you wanted to keep the "Ooh scale" `blockquote::after`.
> 
> After you resolve those and the file time committed here, we'll take another look and get it published ✨

WAVE wasn't catching the contrast issue. That's odd, I will get that fixed. The other issues I have taken care of. I'm wondering why WAVE reported the color contrast of the gradient TL;DR as passing. thanks @5t3ph !

**Comment by colabottles** [comment]
Okay. Made the changes. Hoping the contrast passes and I took care of the issues you pointed out @5t3ph. Let me know if I need ot go back over anything, I'll check back in the morning! 😄

**Comment by 5t3ph** [comment]
Hey @colabottles - I saw your DM a few minutes ago too, sometimes when I know the color is going to be difficult for tools I do a manual pick on it 👍 And the darker part of the red was even below 3 if I recall.

Still a bit of an overlap here, up to you if you want to resolve it!
image

**Comment by colabottles** [comment]
@5t3ph I left that TL;DR in there and moved it around. Let's try one more time! Let me know if I have to change anything else!  \o/

**Pull request merged**
