### PR TITLE
Moccasin stage

### PR DESCRIPTION
**Pull request by GabrielFalcom**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @GabrielFalcom - one small thing: on all of the "button" styles, please allow the outline or create a custom `:focus` style.

**Comment by GabrielFalcom** [comment]
Hi @5t3ph!


> Hi @GabrielFalcom - one small thing: on all of the "button" styles, please allow the outline or create a custom `:focus` style.

Hi @5t3ph!
Added. Thank you :)

**Comment by 5t3ph** [comment]
@GabrielFalcom sorry, I should have also specified that the intent would be to allow a visible outline, or provide an alternate visible focus state. As a sighted keyboard user, the focus state needs to be perceivable visually - thanks!

**Comment by 5t3ph** [comment]
Oh I see you just updated your link so we'll see the updates in a min!

**Review by 5t3ph — APPROVED** [review]
@GabrielFalcom good job on the updates, publishing now!

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Comment by GabrielFalcom** [comment]
Sorry @5t3ph.
I thought that updating the gist would not change the url. And only now did I realize that it has changed.

**Comment by GabrielFalcom** [comment]
Yeaah. Thank you so much @5t3ph.!

**Pull request merged**
