### PR TITLE
Color Stages

### PR DESCRIPTION
**Pull request by clairebaire**
### New Stylesheet Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders a compiled CSS file?

### CODE REVIEW

**Comment by clairebaire** [comment]
@5t3ph Fixed! I forgot that repo was private, but this link should work now! The preview link looks good now :)

**Comment by 5t3ph** [comment]
@clairebaire nice! Missing a visible `.skip-link` but otherwise looks good! I'll watch for a commit with the update 🙌

**Comment by clairebaire** [comment]
@5t3ph Can you trigger the build again? I fixed the skip link, but the link is the same :)

**Comment by 5t3ph** [comment]
*chef's kiss*

Approved!

**Pull request merged**
