### PR TITLE
Submission: iStage style

### PR DESCRIPTION
**Pull request by BaheYaich**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

Real mobile device test performed on iPhone 13 mini, iPhone 11, iPhone 6S and Samsung Galaxy Note 10.

### CODE REVIEW

**Comment by 5t3ph** [comment]
@Whovianpancake this is clever!

The issue for all links is too subtle or non-existent focus styles - please increase contrast of the outlines, ensure all links have at least an outline, and use an outline for the button-styled links as well.

Let me know when your stylesheet is updated to resolve that, and I'll update the preview. Thanks!

Here's your preview: https://deploy-preview-155--moderncss-styles.netlify.app/styles/istage/

**Comment by BaheYaich** [comment]
Hi Steph, 

Thank you for the feedback, and I'm very happy you like it. You are indeed very much correct, these changes make for better visibility. I have just updated my stylesheet, is there any thing else I need to do?

**Comment by 5t3ph** [comment]
@BaheYaich it looks like you removed the file - for it to appear on Style Stage, your stylesheet file needs to have a permanent URL. So, I was unable to rebuild. Do you need to update the path in the JSON?

**Comment by BaheYaich** [comment]
Hi again Steph,

I haven't thought well about the repercussions of changing my username on Github, my bad. URL has been fixed in the JSON now.

**Review by 5t3ph — APPROVED** [review]
@BaheYaich sorry for missing your reply before, publishing now, thanks for participating!

**Pull request merged**
