### PR TITLE
Severe with Rainbow

### PR DESCRIPTION
**Pull request by onlyasmalllizard**
### New Stylesheet Submission: Severe with Rainbow

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @onlyasmalllizard - can you try updating your fork from the main repo? I'm not sure why it hit a build error to make the preview but that may resolve it.

I did look at your CodePen - please resolve the `.profile` covering up page content - it's a pretty significant overlap:
image

Otherwise I think it's in good shape! If you're not sure how to update your fork, you can create a new fork and try again :)

**Comment by onlyasmalllizard** [comment]
Hi @5t3ph, I've updated the stylesheet and I think I've updated the fork. I'm not sure though, so if this doesn't work please let me know and I'll try creating a new fork!

**Review by 5t3ph — APPROVED** [review]
@onlyasmalllizard I think it's good to go! I'm going to cross my fingers the build works for publish ;)

Thank you for participating! If you haven't already, consider subscribing for updates to learn about new styles and features: https://stylestage.dev/subscribe/

**Comment by 5t3ph** [comment]
Hi again @onlyasmalllizard - It's gone a bit off on publish, would you like to address anything or are you ok with it? If you make changes to the CodePen I will redeploy: https://stylestage.dev/styles/severe-with-rainbow/

One change it looks like is to do an `@import` of the fonts in use directly in the CSS - it is not able to use the fonts in CodePen once the stylesheet is moved to the main site 👍

**Comment by onlyasmalllizard** [comment]
Hi @5t3ph, thanks for the heads-up on this! Ironically, I took the import statements out when I moved my code to CodePen because CodePen kept inserting spaces into the font urls and breaking them! I've put them back in now and made a slight change to the .profile section.

**Comment by 5t3ph** [comment]
@onlyasmalllizard I redeployed and I see what you mean on the font URLs, that's silly of them :) Perhaps in CodePen toggle off the auto-formatting (Settings > Behavior > Format on Save) and fix the space in the URLs after that?

I also was wondering if you missed re-adjusting the width of some items like the header h2, the features, and the footer content when you were working on the profile, and if you'd like to adjust it back? Those things are off-center but the profile has enough room :)

**Comment by onlyasmalllizard** [comment]
@5t3ph The auto-formatting was causing the problem, thank you!

I've adjusted the width of everything again, but since it's not displaying the same on CodePen as on the final page, I've had to make my best guess of what won't overlap. Let me know if there are any problems with it!

I really appreciate all of your feedback and help with this :)

**Pull request merged**
