### PR TITLE
feat: add “Transparency” theme

### PR DESCRIPTION
**Pull request by j9t**
Preview: https://hell.meiert.org/temp/stylestage.dev/

Signed-off-by: Jens Oliver Meiert <jens@meiert.com>

### CODE REVIEW

**Comment by 5t3ph** [comment]
Haha, very clever! Double-check that you're happy with the deploy preview then we can merge:
https://deploy-preview-11--moderncss-styles.netlify.app/styles/transparency/

**Comment by j9t** [comment]
Ah, that changes things. I’ve updated https://hell.meiert.org/core/css/stylestage.dev-transparency.css again.

A side note, is there a chance you can point to each original style sheet in a comment? I could imagine there’s value in making it easy to check out the original; in this case it also includes some comments (not so much the introductory ones, but some that give insight into the thinking). Thanks for considering!

**Comment by 5t3ph** [comment]
Redeployed for you to check!

The "View Stylesheet" link next to the "profile" (attribution) block opens the unminified version of your original stylesheet that preserves your comments, and is also the copy that is viewable within the repo 👍

**Comment by j9t** [comment]
Got it, thanks Stephanie!

Something’s wrong with the preview… for some reason (at least) two rules are missing, namely

```css
style {
  display: none !important; /* Yes, to keep with standard selector order */
}

head,
head * {
  display: block !important; /* Yes, to keep it simple */
}
```

Maybe a cache thing, or something on the tooling side? Do you mind checking?

**Comment by 5t3ph** [comment]
Looking at the preview with Inspector, I see both rules but it appears the `head, head *` is overruling due to the order of rules 👍

**Comment by j9t** [comment]
Mmh, I must have tripped over the style sheet/preview disconnect. Can you pull [the latest](https://hell.meiert.org/core/css/stylestage.dev-transparency.css)? (If you can’t see the `style` content anymore and the meta “sidebar” looks properly stacked then it should be good to go.)

**Comment by 5t3ph** [comment]
Looks good, merging!

**Comment by j9t** [comment]
Awesome! Nice working with you on this, and looking forward to seeing more contributions on the site!

**Pull request merged**
