### PR TITLE
dark-purple

### PR DESCRIPTION
**Pull request by Jayashakthi28**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
@Jayashakthi28 - what a fun exploration! A few things to fix up to meet the guidelines.

There is a contrast error of the links in these sections - I think in this case not changing the link color but keeping the underline will be the most accessible solution to meet the guidelines:

image

Additionally, the `.skip-link` needs to be made visible at least on `:focus`

And, all animations need to be stopped when the user has preferenced reduced motion - there's an example of how to do this in the original styles: https://github.com/5t3ph/stylestage/blob/main/src/styles/css/main-stage.css#L84,L91 (you'll have to extend that to include `::before` and `::after` elements)

**Comment by Jayashakthi28** [comment]
I rectified the issues...Could you please check it now?

**Comment by Jayashakthi28** [comment]
Is there any problem with my css? Will my css be published? What should I do now?..Please Help me..

**Comment by 5t3ph** [comment]
@Jayashakthi28 Hi - I'm not seeing any changes after rebuilding, the color contrast does not pass. Did you perhaps forget to push your changes up to GitHub? I do that sometimes! :)

[Here's an example of how to make the skip link work](https://github.com/5t3ph/stylestage/blob/main/src/styles/css/main-stage.css#L632,L650) - it can't be set to `display: none` or it will not ever be able to receive focus. You can test if it works by using your tab key and it should show up as the first thing on the page.

**Comment by Jayashakthi28** [comment]
Mam I have rectified the mentioned issues. Could you please check it now mam?

**Comment by 5t3ph** [comment]
@Jayashakthi28 the color contrast is fixed, but the `.skip-link` still needs resolved. If you use your tab key, it should appear as the first thing on the page on `:focus`, or you can choose to make it visible all of the time. See my previous comment for example styles for that 👍

**Comment by Jayashakthi28** [comment]
Ok mam now I fixed it mam...Sorry for the mistake..Could you please check it now?

**Review by 5t3ph — APPROVED** [review]
@Jayashakthi28 good to publish, thanks for working on the fixes! Publishing now...

**Pull request merged**
