### PR TITLE
Pastels and Columns

### PR DESCRIPTION
**Pull request by CarolMcKay**
### New Stylesheet Submissions:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders a compiled CSS file?

Thanks for the fun practice Steph.

### CODE REVIEW

**Comment by 5t3ph** [comment]
hey @CarolMcKay - some really clever things happening here! I love the insertion of the links to learn about each of the features.

The mobile view has some overflow to resolve (tested on an iPhone 6), and with the sponsor footer in place the bottom of the page content is having some overlap. The sponsor footer isn't available to style but you can make adjustments to postion it correctly at the bottom.

And are a few things to resolve to meet the guidelines around accessibility:
- My least favorite criticism to give because it goes against your creative vision (sorry!) but the headline with the graphic means it is not passing contrast requirements
- Similarly, the buttons over the flower photo aren't passing as buttons need to have at least 3:1 contrast with their surrounding
- The red buttons against the yellow are also not passing for the same reason

Let me know when these are resolved and I'll redeploy the preview: https://deploy-preview-47--moderncss-styles.netlify.app/styles/pastels-and-columns/#main

**Comment by 5t3ph** [comment]
Hi @CarolMcKay - checking in if you plan to resolve these issues, thanks!

**Comment by CarolMcKay** [comment]
Hi Stephanie,

Thank you for your feedback the other day, much appreciated.

I will be resolving those issues, it is my side project and am really enjoying doing it.

Just out of curiosity, is there a deadline on this project?

thanks,
Carol

**Comment by 5t3ph** [comment]
@CarolMcKay no deadline, just checking in! I'm so glad you're enjoying it 😊

**Comment by CarolMcKay** [comment]
Hi Stephanie,
I have had an attempt to improve a11y, please note there is also a dark mode.
Thankyou, I hope you are not becoming overwhelmed.

**Pull request merged**
