### PR TITLE
added new stylesheet - studious umbrella

### PR DESCRIPTION
**Pull request by anushas-dev**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [ ] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
@anushas-dev there are unfortunately some color contrast issues, and the pattern makes the text a bit hard to read as well. Please resolve and update your stylesheet and let me know when it's ready and I'll update the preview to check again.

It's also best to retain the underline for links to help them stand out from regular text content, or provide another visual cue.

Let me know if you need help checking the contrast! I recommend browser extensions like WAVE, aXe, or Accessibility Insights.

**Comment by anushas-dev** [comment]
Thank you @5t3ph, I tried the Accessibility Insights for Web | Edge - Fast Pass, no issues from automated checks currently. Please do let me know if you have any other recommendations :)

**Comment by 5t3ph** [comment]
@anushas-dev it's possible some style didn't come through to style stage as you intended, here's the page checked with WAVE where each red icon indicates a contrast issue:
image

Here's the link to check which is what will be displayed for Style Stage: https://deploy-preview-154--moderncss-styles.netlify.app/styles/studious-umbrella/

**Comment by 5t3ph** [comment]
@anushas-dev closing for now but if you find time to address the contrast, please re-submit, thanks!

**Pull request closed without merging**
