### PR TITLE
Added Color-Combo.json

### PR DESCRIPTION
**Pull request by aniketsingh98571**
### New Stylesheet Submission:

Color-Combo.json

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

@5t3ph Please review my PR, and do let me know if any changes required.

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @aniketsingh98571,

Here is your preview - did you perhaps just add the wrong stylesheet link? https://deploy-preview-63--moderncss-styles.netlify.app/styles/aniket-singh/

If you didn't link the wrong stylesheet, there may be a misunderstanding of what the `stylesheet` is for :) The idea of this repo is to re-style the HTML that is found at [StyleStage.dev](https://stylestage.dev). You can read more details on the site about how it all works, but let me know if you have questions!

Also if you do have a submission, you'll want to update the `title` field in the JSON file to the name of your stylesheet, which perhaps was supposed to be "Color Combo"?

**Comment by 5t3ph** [comment]
Hi @aniketsingh98571 - checking in if you plan to resolve the issue, thanks.

**Comment by aniketsingh98571** [comment]
@5t3ph I have been working on it, please give me some time I will revert back to you. Sorry for "No response".

**Comment by 5t3ph** [comment]
@aniketsingh98571 perfect, I look forward to your final styles!

**Comment by 5t3ph** [comment]
Closing since this was reopened as #79

**Pull request closed without merging**
