### PR TITLE
Soff.css

### PR DESCRIPTION
**Pull request by beatricebock**
### New Stylesheet Submission:

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other files using the same name as yours?
- [x] Have you filled in at least the required data for `title`, `author`, and `stylesheet`?
- [x] Is the value of `stylesheet` a full URL that is publicly accessible and renders an unminified, compiled CSS file?
- [x] Do your styles pass proper contrast for accessibility?
- [x] Have you included `@media (prefers-reduced-motion: reduce)` to remove animations on `*,*::before,*::after`?
- [x] Did you style the `.skip-link`?
- [x] Have you checked on a real mobile device to ensure your responsive design doesn't cause overlaps or overflow scrolling?

### CODE REVIEW

**Comment by 5t3ph** [comment]
Hi @beatricebock - I pulled this down locally since the build is failing and the build works locally (I think some recent changes caused some issues between the main site and forks).

The hover state on the "Featured Styles" doesn't change the text color, so that needs a little update.

Also, perhaps you could re-look at the small viewport styles - the font-size too small to be very legible, so perhaps the nav needs a new location on small viewports to gain more screen width for the main text content?

Let me know when you've made some updates and I'll take another look!

**Comment by beatricebock** [comment]
Ooh good ideas, @5t3ph, thanks! I'll update you once I've made some changes :)

**Comment by 5t3ph** [comment]
@beatricebock great! I tried again and the preview works now, just for your reference: https://deploy-preview-54--moderncss-styles.netlify.app/styles/soff/

**Comment by beatricebock** [comment]
Hi @5t3ph, I've updated the styles based on your suggestions:

- Font-size on mobile is now 15px from 12px
- Nav menu is now fixed to the bottom of the page, and side-scrolls
- There is a hover state for the Featured Styles, but only on the links to the actual styles. I updated the styling so it's less likely to be mistaken for a whole button.

Take a look and let me know what you think. Thank you for your ideas :)

**Comment by 5t3ph** [comment]
Great job on the updates @beatricebock!

Here is the issue I was trying to describe earlier, I should have included a screenshot then, sorry!:
image

**Comment by beatricebock** [comment]
> Great job on the updates @beatricebock!
> 
> Here is the issue I was trying to describe earlier, I should have included a screenshot then, sorry!:
> image

Ooh that's odd, could you share what your browser/device is? I tested on my Mac, in Firefox, safari, chrome and they all seem to be working fine. Great eye!

**Comment by 5t3ph** [comment]
@beatricebock - I'm in latest Chrome on Mac. I redeployed in case I had old styles but still saw it, so I cracked open Inspector and when I remove the `z-index: 100` on `a` it works. You may have to scope removing it to just those feature cards because I see that removing it breaks the effect for the other links that are in-paragraph.

**Comment by 5t3ph** [comment]
Hi @beatricebock - let me know if my last note made sense or if you need any additional help troubleshooting this, thanks! I'm excited to add this to the showcase 🤩

**Comment by 5t3ph** [comment]
Hi @beatricebock - Just letting you know I will be closing this in the next few days if you are not able to make edits at this time, but you are welcome to resubmit in the future!

**Comment by beatricebock** [comment]
Hi @5t3ph thanks for following! So sorry it's been awhile, I'm working on it right now to get it scoped and fixed. Thanks for being so patient!

**Pull request merged**
